### ISSUE TITLE
worker network problem

### ISSUE THREAD

**Issue by caozhiyuan** [apprenda/kubernetes-ovn-heterogeneous-cluster#22]
33s	33s	1	{kubelet k8snode21}	spec.containers{kubedns}	Normal	Pulled		Container image "gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.13.0" already present on machine
  32s	32s	1	{kubelet k8snode21}	spec.containers{kubedns}	Normal	Created		Created container with docker id 6bdd4bce7d37; Security:[seccomp=unconfined]
  32s	32s	1	{kubelet k8snode21}	spec.containers{dnsmasq}	Normal	Pulled		Container image "gcr.io/google_containers/k8s-dns-dnsmasq-amd64:1.13.0" already present on machine
  32s	32s	1	{kubelet k8snode21}	spec.containers{kubedns}	Normal	Started		Started container with docker id 6bdd4bce7d37
  31s	31s	1	{kubelet k8snode21}	spec.containers{dnsmasq}	Normal	Created		Created container with docker id ba972e97f6b9; Security:[seccomp=unconfined]
  30s	30s	1	{kubelet k8snode21}	spec.containers{dnsmasq}	Normal	Started		Started container with docker id ba972e97f6b9
  30s	30s	1	{kubelet k8snode21}	spec.containers{sidecar}	Normal	Pulled		Container image "gcr.io/google_containers/k8s-dns-sidecar-amd64:1.13.0" already present on machine
  30s	30s	1	{kubelet k8snode21}	spec.containers{sidecar}	Normal	Created		Created container with docker id 764cf068ef9e; Security:[seccomp=unconfined]
  29s	29s	1	{kubelet k8snode21}	spec.containers{sidecar}	Normal	Started		Started container with docker id 764cf068ef9e
  28s	8s	3	{kubelet k8snode21}	spec.containers{kubedns}	Warning	Unhealthy	Readiness probe failed: Get http://10.244.2.3:8081/readiness: dial tcp 10.244.2.3:8081: getsockopt: connection refused

**Comment by pires** [comment]
That's not a worker network problem but the readiness probe for kubedns failing. You need to check the logs for kubedns container to understand what's going on.

**Comment by caozhiyuan** [comment]
k8s-dns-kube-dns-amd64:1.13.0 logs as follows but i have not idea how to deal with it
I0603 12:55:55.053525       1 dns.go:49] version: v1.5.2-beta.0+$Format:%h$
I0603 12:55:55.056114       1 server.go:65] Using configuration read from directory: /kube-dns-config%!(EXTRA time.Duration=10s)
I0603 12:55:55.056187       1 server.go:104] FLAG: --alsologtostderr="false"
I0603 12:55:55.056202       1 server.go:104] FLAG: --config-dir="/kube-dns-config"
I0603 12:55:55.056208       1 server.go:104] FLAG: --config-map=""
I0603 12:55:55.056211       1 server.go:104] FLAG: --config-map-namespace="kube-system"
I0603 12:55:55.056214       1 server.go:104] FLAG: --config-period="10s"
I0603 12:55:55.056235       1 server.go:104] FLAG: --dns-bind-address="0.0.0.0"
I0603 12:55:55.056240       1 server.go:104] FLAG: --dns-port="10053"
I0603 12:55:55.056246       1 server.go:104] FLAG: --domain="cluster.local."
I0603 12:55:55.056251       1 server.go:104] FLAG: --federations=""
I0603 12:55:55.056255       1 server.go:104] FLAG: --healthz-port="8081"
I0603 12:55:55.056259       1 server.go:104] FLAG: --initial-sync-timeout="1m0s"
I0603 12:55:55.056262       1 server.go:104] FLAG: --kube-master-url=""
I0603 12:55:55.056266       1 server.go:104] FLAG: --kubecfg-file=""
I0603 12:55:55.056269       1 server.go:104] FLAG: --log-backtrace-at=":0"
I0603 12:55:55.056274       1 server.go:104] FLAG: --log-dir=""
I0603 12:55:55.056278       1 server.go:104] FLAG: --log-flush-frequency="5s"
I0603 12:55:55.056281       1 server.go:104] FLAG: --logtostderr="true"
I0603 12:55:55.056285       1 server.go:104] FLAG: --stderrthreshold="2"
I0603 12:55:55.056288       1 server.go:104] FLAG: --v="2"
I0603 12:55:55.056291       1 server.go:104] FLAG: --version="false"
I0603 12:55:55.056296       1 server.go:104] FLAG: --vmodule=""
I0603 12:55:55.056347       1 server.go:149] Starting SkyDNS server (0.0.0.0:10053)
I0603 12:55:55.056627       1 server.go:159] Skydns metrics enabled (/metrics:10055)
I0603 12:55:55.056670       1 dns.go:147] Starting endpointsController
I0603 12:55:55.056674       1 dns.go:150] Starting serviceController
I0603 12:55:55.057101       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0603 12:55:55.057127       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0603 12:55:55.557369       1 dns.go:174] DNS server not ready, retry in 500 milliseconds
I0603 12:55:56.057095       1 dns.go:174] DNS server not ready, retry in 500 milliseconds
I0603 12:55:56.557321       1 dns.go:174] DNS server not ready, retry in 500 milliseconds
I0603 12:55:57.057539       1 dns.go:174] DNS server not ready, retry in 500 milliseconds

**Comment by caozhiyuan** [comment]
I test this demo in vm (ubuntu)   my ip is 192.168.3.xx  dns is 192.168.3.1

**Comment by caozhiyuan** [comment]
export K8S_API_SERVICE_IP=10.100.0.1 
E0603 13:55:21.999399 1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.100.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.100.0.1:443: i/o timeout

is K8S_API_SERVICE internal IP is 10.100.0.1 ?
